**Import Required Library:**

In [1]:
import numpy as np
import pandas as pd

**Read dataset**

In [2]:
df=pd.read_csv('student.csv')

**Show DataSet**

In [3]:
df.head()

gender NationalITy PlaceofBirth     StageID GradeID SectionID Topic  \
0      M          KW       KuwaIT  lowerlevel    G-04         A    IT   
1      M          KW       KuwaIT  lowerlevel    G-04         A    IT   
2      M          KW       KuwaIT  lowerlevel    G-04         A    IT   
3      M          KW       KuwaIT  lowerlevel    G-04         A    IT   
4      M          KW       KuwaIT  lowerlevel    G-04         A    IT   

  Semester Relation  raisedhands  VisITedResources  AnnouncementsView  \
0        F   Father           15                16                  2   
1        F   Father           20                20                  3   
2        F   Father           10                 7                  0   
3        F   Father           30                25                  5   
4        F   Father           40                50                 12   

   Discussion ParentAnsweringSurvey ParentschoolSatisfaction  \
0          20                   Yes                     Good   
1          25                   Yes                     Good   
2          30                    No                      Bad   
3          35                    No                      Bad   
4          50                    No                      Bad   

  StudentAbsenceDays Class  
0            Under-7     M  
1            Under-7     M  
2            Above-7     L  
3            Above-7     L  
4            Above-7     M

In [4]:
df['Class'].value_counts()

M    211
H    142
L    127
Name: Class, dtype: int64

**check columns Types**

In [6]:
cat_data=df.select_dtypes(include='object')

**Separate Categorical columns**

In [7]:
cat_data.head()

gender NationalITy PlaceofBirth     StageID GradeID SectionID Topic  \
0      M          KW       KuwaIT  lowerlevel    G-04         A    IT   
1      M          KW       KuwaIT  lowerlevel    G-04         A    IT   
2      M          KW       KuwaIT  lowerlevel    G-04         A    IT   
3      M          KW       KuwaIT  lowerlevel    G-04         A    IT   
4      M          KW       KuwaIT  lowerlevel    G-04         A    IT   

  Semester Relation ParentAnsweringSurvey ParentschoolSatisfaction  \
0        F   Father                   Yes                     Good   
1        F   Father                   Yes                     Good   
2        F   Father                    No                      Bad   
3        F   Father                    No                      Bad   
4        F   Father                    No                      Bad   

  StudentAbsenceDays Class  
0            Under-7     M  
1            Under-7     M  
2            Above-7     L  
3            Above-7     L  
4            Above-7     M

**Separate Numerical Columns**

In [10]:
num_data=df.select_dtypes(exclude='object')

In [12]:
num_data.head()

raisedhands  VisITedResources  AnnouncementsView  Discussion
0           15                16                  2          20
1           20                20                  3          25
2           10                 7                  0          30
3           30                25                  5          35
4           40                50                 12          50

**Covert Categorical Columns data to Numerical Using LabelEncoder**

In [14]:
from sklearn.preprocessing import LabelEncoder

In [15]:
lb=LabelEncoder()

In [17]:
cat_data=cat_data.apply(lb.fit_transform)

In [18]:
cat_data.head()

gender  NationalITy  PlaceofBirth  StageID  GradeID  SectionID  Topic  \
0       1            4             4        2        1          0      7   
1       1            4             4        2        1          0      7   
2       1            4             4        2        1          0      7   
3       1            4             4        2        1          0      7   
4       1            4             4        2        1          0      7   

   Semester  Relation  ParentAnsweringSurvey  ParentschoolSatisfaction  \
0         0         0                      1                         1   
1         0         0                      1                         1   
2         0         0                      0                         0   
3         0         0                      0                         0   
4         0         0                      0                         0   

   StudentAbsenceDays  Class  
0                   1      2  
1                   1      2  
2                   0      1  
3                   0      1  
4                   0      2

**Add After Converting Categorical to Numerical Columns**

In [19]:
new_data=pd.concat([cat_data,num_data],axis=1)

In [20]:
new_data.head()

gender  NationalITy  PlaceofBirth  StageID  GradeID  SectionID  Topic  \
0       1            4             4        2        1          0      7   
1       1            4             4        2        1          0      7   
2       1            4             4        2        1          0      7   
3       1            4             4        2        1          0      7   
4       1            4             4        2        1          0      7   

   Semester  Relation  ParentAnsweringSurvey  ParentschoolSatisfaction  \
0         0         0                      1                         1   
1         0         0                      1                         1   
2         0         0                      0                         0   
3         0         0                      0                         0   
4         0         0                      0                         0   

   StudentAbsenceDays  Class  raisedhands  VisITedResources  \
0                   1      2           15                16   
1                   1      2           20                20   
2                   0      1           10                 7   
3                   0      1           30                25   
4                   0      2           40                50   

   AnnouncementsView  Discussion  
0                  2          20  
1                  3          25  
2                  0          30  
3                  5          35  
4                 12          50

In [21]:
new_data['Class'].value_counts()

2    211
0    142
1    127
Name: Class, dtype: int64

**Train A model**

**select a resultant columns**

In [22]:
x=new_data.drop(['Class'],axis=1)

In [23]:
y=new_data['Class']

In [24]:
from sklearn.model_selection import train_test_split

In [27]:
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.33,random_state=42)

In [28]:
xtrain.head()

gender  NationalITy  PlaceofBirth  StageID  GradeID  SectionID  Topic  \
118       0            4             4        2        0          2      7   
114       1            4             4        2        0          1      7   
265       0            3             3        1        3          0      3   
426       1            3             3        1        5          0      2   
144       1            4             4        1        4          0      9   

     Semester  Relation  ParentAnsweringSurvey  ParentschoolSatisfaction  \
118         0         1                      1                         1   
114         0         0                      0                         0   
265         1         1                      0                         0   
426         0         1                      1                         1   
144         1         0                      0                         0   

     StudentAbsenceDays  raisedhands  VisITedResources  AnnouncementsView  \
118                   0           24                35                 23   
114                   0           11                 2                  0   
265                   1           79                84                 82   
426                   0           80                80                 62   
144                   0           10                10                 15   

     Discussion  
118          22  
114          50  
265          37  
426          11  
144          19

In [29]:
xtest.head()

gender  NationalITy  PlaceofBirth  StageID  GradeID  SectionID  Topic  \
73        0            4             4        1        4          0      3   
414       0            5             5        1        4          1      1   
394       1            3             7        1        4          0      1   
277       1            7             3        1        3          0      3   
399       1            7             7        1        4          0      1   

     Semester  Relation  ParentAnsweringSurvey  ParentschoolSatisfaction  \
73          0         0                      1                         0   
414         0         1                      0                         1   
394         0         1                      1                         1   
277         1         1                      1                         1   
399         1         0                      1                         1   

     StudentAbsenceDays  raisedhands  VisITedResources  AnnouncementsView  \
73                    0           19                30                 26   
414                   0           10                 9                  2   
394                   1           78                91                 50   
277                   1           92                31                 42   
399                   1           89                92                 89   

     Discussion  
73           19  
414           1  
394          40  
277          27  
399          83

In [31]:
ytrain.head()

118    2
114    1
265    0
426    2
144    1
Name: Class, dtype: int32

In [32]:
ytest.head()

73     2
414    1
394    0
277    0
399    0
Name: Class, dtype: int32

# Apply Guassian Naive Bayes :

In [33]:
from sklearn.naive_bayes import GaussianNB

In [34]:
nb=GaussianNB()

In [35]:
nb.fit(xtrain,ytrain)

GaussianNB()

In [36]:
y_pred=nb.predict(xtest)

In [37]:
y_pred

array([1, 1, 0, 2, 0, 1, 1, 1, 2, 2, 0, 0, 0, 1, 0, 0, 1, 2, 1, 2, 0, 0,
       1, 2, 1, 1, 0, 2, 1, 2, 2, 2, 1, 2, 2, 2, 1, 2, 0, 2, 2, 0, 1, 0,
       0, 1, 0, 0, 0, 1, 2, 2, 1, 2, 2, 2, 1, 0, 2, 1, 2, 1, 1, 0, 2, 2,
       1, 0, 1, 0, 1, 0, 2, 2, 2, 1, 2, 1, 1, 0, 0, 2, 1, 0, 0, 1, 2, 1,
       1, 2, 0, 2, 2, 2, 1, 0, 1, 2, 0, 1, 2, 1, 2, 0, 2, 0, 0, 1, 2, 1,
       2, 2, 2, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 2, 1, 2, 1, 1, 2, 0, 2, 1,
       1, 1, 1, 2, 2, 1, 2, 1, 1, 2, 1, 1, 0, 1, 0, 0, 2, 2, 0, 0, 2, 2,
       0, 1, 0, 0, 0])

In [39]:
pd.DataFrame({'Actual':ytest,"Predict":y_pred}).head()

Actual  Predict
73        2        1
414       1        1
394       0        0
277       0        2
399       0        0

# Show Accuracy:

In [40]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [41]:
accuracy_score(ytest,y_pred)

0.710691823899371

In [42]:
confusion_matrix(ytest,y_pred)

array([[28,  0,  8],
       [ 0, 42,  4],
       [19, 15, 43]], dtype=int64)

In [43]:
print(classification_report(ytest,y_pred))

              precision    recall  f1-score   support

           0       0.60      0.78      0.67        36
           1       0.74      0.91      0.82        46
           2       0.78      0.56      0.65        77

    accuracy                           0.71       159
   macro avg       0.70      0.75      0.71       159
weighted avg       0.73      0.71      0.70       159



# Cross Validation Score:

In [44]:
from sklearn.model_selection import cross_val_score

In [45]:
a=cross_val_score(nb,x,y,cv=10)

In [46]:
a

array([0.66666667, 0.64583333, 0.64583333, 0.72916667, 0.625     ,
       0.6875    , 0.6875    , 0.8125    , 0.79166667, 0.64583333])

In [47]:
a.mean()

0.69375